import type { AtlasProject, MemoryEdge, MemoryNode, MockAiChat, TimelineMoment } from './types'

export const mockAiChats: MockAiChat[] = [
  {
    id: 'chat-voice-second-brain',
    surface: 'ChatGPT',
    title: 'Voice-first second brain',
    userMessage: '我想做一个能用语音快速记录想法的 AI second brain，最好能帮我管理任务和灵感。',
    aiMessage:
      '先把语音作为入口，沉淀用户输入、AI 输出、任务、开放问题和生成物。后续可以把这些内容转成知识图谱。',
    capturedAt: '2026-06-26T10:18:00+08:00',
    projectId: 'project-atlas',
    extractedNodeIds: ['idea-voice-entry', 'idea-graph-asset', 'task-capture-console'],
  },
  {
    id: 'chat-agent-harness',
    surface: 'Claude',
    title: 'Agent Harness JD analysis',
    userMessage: '我要申请 DeepSeek Agent Harness PM，帮我挖一个能体现 agent 产品思考的项目。',
    aiMessage:
      '重点不是普通效率工具，而是 agent 时代的 context engineering：捕获人和 AI 协作过程，并把历史变成下一次 agent 可用的上下文。',
    capturedAt: '2026-06-28T09:42:00+08:00',
    projectId: 'project-atlas',
    extractedNodeIds: ['project-deepseek', 'idea-agent-context', 'decision-jd-narrative'],
  },
  {
    id: 'chat-context-bridge',
    surface: 'Codex',
    title: 'Context bridge prototype',
    userMessage: '如果只是帮 agent 读上一段聊天，这个项目是不是太工具化了？',
    aiMessage:
      '是的。更强的价值是把长期 AI 协作轨迹变成可视化资产：项目、想法、决策、任务、作品和偏好都可以被回看和复用。',
    capturedAt: '2026-06-28T11:15:00+08:00',
    projectId: 'project-atlas',
    extractedNodeIds: ['decision-shift-to-atlas', 'idea-memory-graph', 'preference-product-value'],
  },
  {
    id: 'chat-replay-mode',
    surface: 'ChatGPT',
    title: 'Replay the idea growth',
    userMessage: '我希望这个产品有情绪价值，不只是保存聊天。',
    aiMessage:
      '加入 Replay Mode：用户能看到一个想法如何从一句 prompt 长成项目。它让个人 AI 使用痕迹变成有温度的成长记录。',
    capturedAt: '2026-06-28T12:04:00+08:00',
    projectId: 'project-atlas',
    extractedNodeIds: ['artifact-replay-mode', 'idea-evolving-preferences', 'question-memory-trust'],
  },
  {
    id: 'chat-extension-capture',
    surface: 'Cursor',
    title: 'Extension capture path',
    userMessage: '现有 extension 和 ingest API 应该留着吗？',
    aiMessage:
      '保留。它们是 Capture 层 proof point，但首页应该优先展示 Memory Graph、Timeline 和 Project Lens，而不是插件配置。',
    capturedAt: '2026-06-28T13:36:00+08:00',
    projectId: 'project-atlas',
    extractedNodeIds: ['tool-browser-extension', 'decision-capture-supporting-flow', 'task-ingestion-hardening'],
  },
  {
    id: 'chat-agent-export',
    surface: 'OpenClaw',
    title: 'Export project context',
    userMessage: '最终怎么和 agent harness 连接上？',
    aiMessage:
      '把 Project Lens 里的摘要、关键决策、开放问题、任务和 artifacts 导出成 agent context，让 agent 能从真实项目记忆继续工作。',
    capturedAt: '2026-06-28T15:21:00+08:00',
    projectId: 'project-atlas',
    extractedNodeIds: ['artifact-project-context-export', 'task-export-context', 'idea-agent-context'],
  },
]

export const memoryNodes: MemoryNode[] = [
  {
    id: 'person-user',
    type: 'person',
    title: 'Sylvie',
    summary: 'AI-heavy builder turning repeated AI collaboration into a personal product asset.',
    evidence: ['Repeatedly connects PM portfolio, agent memory, and visual thinking tools.'],
    confidence: 0.9,
    createdAt: '2026-06-26T10:18:00+08:00',
    updatedAt: '2026-06-28T15:21:00+08:00',
    x: 445,
    y: 270,
    sourceChatIds: ['chat-voice-second-brain', 'chat-agent-harness', 'chat-context-bridge'],
  },
  {
    id: 'project-atlas',
    type: 'project',
    title: 'AI Memory Atlas',
    summary: 'A visual memory system for long-term human-AI collaboration.',
    evidence: ['Position shifted from voice assistant to memory graph product.'],
    confidence: 0.96,
    createdAt: '2026-06-28T11:15:00+08:00',
    updatedAt: '2026-06-28T15:21:00+08:00',
    x: 520,
    y: 255,
    sourceChatIds: ['chat-context-bridge', 'chat-replay-mode', 'chat-agent-export'],
  },
  {
    id: 'project-deepseek',
    type: 'project',
    title: 'DeepSeek Agent Harness Application',
    summary: 'Portfolio narrative showing PM sense around agent memory and context engineering.',
    evidence: ['User asked for a project aligned with DeepSeek Agent Harness PM.'],
    confidence: 0.86,
    createdAt: '2026-06-28T09:42:00+08:00',
    updatedAt: '2026-06-28T13:36:00+08:00',
    x: 685,
    y: 130,
    sourceChatIds: ['chat-agent-harness'],
  },
  {
    id: 'idea-voice-entry',
    type: 'idea',
    title: 'Voice as Capture Entry',
    summary: 'Voice remains useful as one input path, but not the core product promise.',
    evidence: ['The earliest concept centered on voice-first capture.'],
    confidence: 0.77,
    createdAt: '2026-06-26T10:18:00+08:00',
    updatedAt: '2026-06-28T11:15:00+08:00',
    x: 205,
    y: 115,
    sourceChatIds: ['chat-voice-second-brain'],
  },
  {
    id: 'idea-memory-graph',
    type: 'idea',
    title: 'Human-AI Memory Graph',
    summary: 'Projects, decisions, ideas, tasks, artifacts, preferences, and questions become visible graph nodes.',
    evidence: ['The new product direction centers on a growing personal AI memory graph.'],
    confidence: 0.95,
    createdAt: '2026-06-28T11:15:00+08:00',
    updatedAt: '2026-06-28T15:21:00+08:00',
    x: 520,
    y: 105,
    sourceChatIds: ['chat-context-bridge', 'chat-replay-mode'],
  },
  {
    id: 'idea-agent-context',
    type: 'idea',
    title: 'Agent-Ready Project Context',
    summary: 'Project memory can be exported back to agents so work continues from durable context.',
    evidence: ['Agent harness connection comes through Project Lens context export.'],
    confidence: 0.89,
    createdAt: '2026-06-28T09:42:00+08:00',
    updatedAt: '2026-06-28T15:21:00+08:00',
    x: 760,
    y: 395,
    sourceChatIds: ['chat-agent-harness', 'chat-agent-export'],
  },
  {
    id: 'decision-shift-to-atlas',
    type: 'decision',
    title: 'Reposition Around Memory Asset',
    summary: 'The project should sell long-term AI memory value, not previous-chat convenience.',
    evidence: ['User agreed this direction has more product value.'],
    confidence: 0.94,
    createdAt: '2026-06-28T11:15:00+08:00',
    updatedAt: '2026-06-28T11:15:00+08:00',
    x: 350,
    y: 250,
    sourceChatIds: ['chat-context-bridge'],
  },
  {
    id: 'decision-capture-supporting-flow',
    type: 'decision',
    title: 'Capture Becomes Supporting Flow',
    summary: 'Extension and ingest remain proof points, while the main UI becomes graph-first.',
    evidence: ['Existing extension should be retained as Capture layer infrastructure.'],
    confidence: 0.88,
    createdAt: '2026-06-28T13:36:00+08:00',
    updatedAt: '2026-06-28T13:36:00+08:00',
    x: 325,
    y: 400,
    sourceChatIds: ['chat-extension-capture'],
  },
  {
    id: 'artifact-replay-mode',
    type: 'artifact',
    title: 'Replay Mode',
    summary: 'A view that replays how an idea grew from first prompt into a project direction.',
    evidence: ['Replay gives the product emotional value and narrative strength.'],
    confidence: 0.84,
    createdAt: '2026-06-28T12:04:00+08:00',
    updatedAt: '2026-06-28T12:04:00+08:00',
    x: 560,
    y: 430,
    sourceChatIds: ['chat-replay-mode'],
  },
  {
    id: 'artifact-project-context-export',
    type: 'artifact',
    title: 'Project Context Export',
    summary: 'A compact context pack containing summary, decisions, open questions, tasks, and artifacts.',
    evidence: ['Export Project Context is the bridge back to agent harness workflows.'],
    confidence: 0.87,
    createdAt: '2026-06-28T15:21:00+08:00',
    updatedAt: '2026-06-28T15:21:00+08:00',
    x: 815,
    y: 260,
    sourceChatIds: ['chat-agent-export'],
  },
  {
    id: 'task-capture-console',
    type: 'task',
    title: 'Build Capture Console',
    summary: 'Let users paste or capture AI conversations as raw evidence.',
    evidence: ['Manual paste and extension capture remain MVP inputs.'],
    confidence: 0.8,
    createdAt: '2026-06-26T10:18:00+08:00',
    updatedAt: '2026-06-28T13:36:00+08:00',
    x: 160,
    y: 315,
    sourceChatIds: ['chat-voice-second-brain'],
  },
  {
    id: 'task-export-context',
    type: 'task',
    title: 'Ship Export Project Context',
    summary: 'Generate agent-ready project context from selected graph memory.',
    evidence: ['The project should still connect to agent harness as a bonus workflow.'],
    confidence: 0.83,
    createdAt: '2026-06-28T15:21:00+08:00',
    updatedAt: '2026-06-28T15:21:00+08:00',
    x: 660,
    y: 520,
    sourceChatIds: ['chat-agent-export'],
  },
  {
    id: 'task-ingestion-hardening',
    type: 'task',
    title: 'Harden Capture Diagnostics',
    summary: 'Make DOM, network, and manual capture failures visible and recoverable.',
    evidence: ['Extension capture can break when third-party AI pages change.'],
    confidence: 0.74,
    createdAt: '2026-06-28T13:36:00+08:00',
    updatedAt: '2026-06-28T13:36:00+08:00',
    x: 185,
    y: 475,
    sourceChatIds: ['chat-extension-capture'],
  },
  {
    id: 'question-memory-trust',
    type: 'question',
    title: 'How Does The User Trust The Graph?',
    summary: 'Every node needs visible evidence, confidence, and source chat provenance.',
    evidence: ['The graph must avoid feeling like arbitrary AI-generated organization.'],
    confidence: 0.81,
    createdAt: '2026-06-28T12:04:00+08:00',
    updatedAt: '2026-06-28T12:04:00+08:00',
    x: 425,
    y: 540,
    sourceChatIds: ['chat-replay-mode'],
  },
  {
    id: 'preference-product-value',
    type: 'preference',
    title: 'Prefer Product Value Over Tooling',
    summary: 'The user gravitates toward emotionally resonant product assets over narrow utility plugins.',
    evidence: ['User said the atlas direction has more product value.'],
    confidence: 0.92,
    createdAt: '2026-06-28T11:15:00+08:00',
    updatedAt: '2026-06-28T11:15:00+08:00',
    x: 640,
    y: 600,
    sourceChatIds: ['chat-context-bridge'],
  },
  {
    id: 'idea-graph-asset',
    type: 'idea',
    title: 'AI Usage Becomes An Asset',
    summary: 'Daily AI collaboration should compound into memory rather than disappear into scattered chats.',
    evidence: ['The core pain is that many AI conversations do not become user-owned assets.'],
    confidence: 0.93,
    createdAt: '2026-06-26T10:18:00+08:00',
    updatedAt: '2026-06-28T15:21:00+08:00',
    x: 430,
    y: 70,
    sourceChatIds: ['chat-voice-second-brain', 'chat-context-bridge'],
  },
  {
    id: 'tool-browser-extension',
    type: 'tool',
    title: 'Browser Extension Capture',
    summary: 'Content script and network hook capture prompt-answer pairs from supported AI surfaces.',
    evidence: ['Existing repo has extension and ingest API path.'],
    confidence: 0.76,
    createdAt: '2026-06-28T13:36:00+08:00',
    updatedAt: '2026-06-28T13:36:00+08:00',
    x: 110,
    y: 210,
    sourceChatIds: ['chat-extension-capture'],
  },
  {
    id: 'idea-evolving-preferences',
    type: 'preference',
    title: 'Show Evolving Taste',
    summary: 'The atlas should reveal recurring interests and product judgment over time.',
    evidence: ['Repeated themes include agent memory, PM workflow, portfolio, and visual thinking.'],
    confidence: 0.85,
    createdAt: '2026-06-28T12:04:00+08:00',
    updatedAt: '2026-06-28T12:04:00+08:00',
    x: 795,
    y: 590,
    sourceChatIds: ['chat-replay-mode'],
  },
  {
    id: 'failure-lost-chats',
    type: 'failure',
    title: 'Lost Chat Value',
    summary: 'Useful AI judgments scatter across chat histories and fail to become reusable context.',
    evidence: ['The user pain is not copy-paste, but losing the long-term trajectory of AI work.'],
    confidence: 0.9,
    createdAt: '2026-06-28T11:15:00+08:00',
    updatedAt: '2026-06-28T11:15:00+08:00',
    x: 295,
    y: 105,
    sourceChatIds: ['chat-context-bridge'],
  },
]

export const memoryEdges: MemoryEdge[] = [
  { id: 'edge-user-project', from: 'person-user', to: 'project-atlas', type: 'belongs_to', evidence: 'Active project owner' },
  { id: 'edge-deepseek-atlas', from: 'project-deepseek', to: 'project-atlas', type: 'supports', evidence: 'Portfolio narrative' },
  { id: 'edge-lost-graph', from: 'failure-lost-chats', to: 'idea-graph-asset', type: 'led_to', evidence: 'Pain led to graph asset idea' },
  { id: 'edge-voice-graph', from: 'idea-voice-entry', to: 'idea-graph-asset', type: 'led_to', evidence: 'Voice shifted from core to input layer' },
  { id: 'edge-asset-memory', from: 'idea-graph-asset', to: 'idea-memory-graph', type: 'led_to' },
  { id: 'edge-memory-project', from: 'idea-memory-graph', to: 'project-atlas', type: 'supports' },
  { id: 'edge-shift-project', from: 'decision-shift-to-atlas', to: 'project-atlas', type: 'generated_from' },
  { id: 'edge-capture-support', from: 'decision-capture-supporting-flow', to: 'project-atlas', type: 'supports' },
  { id: 'edge-extension-capture', from: 'tool-browser-extension', to: 'task-capture-console', type: 'supports' },
  { id: 'edge-capture-decision', from: 'task-capture-console', to: 'decision-capture-supporting-flow', type: 'led_to' },
  { id: 'edge-replay-project', from: 'artifact-replay-mode', to: 'project-atlas', type: 'supports' },
  { id: 'edge-context-agent', from: 'artifact-project-context-export', to: 'idea-agent-context', type: 'supports' },
  { id: 'edge-export-task', from: 'task-export-context', to: 'artifact-project-context-export', type: 'resolved_by' },
  { id: 'edge-trust-replay', from: 'question-memory-trust', to: 'artifact-replay-mode', type: 'supports' },
  { id: 'edge-preference-decision', from: 'preference-product-value', to: 'decision-shift-to-atlas', type: 'supports' },
  { id: 'edge-taste-insight', from: 'idea-evolving-preferences', to: 'preference-product-value', type: 'revisited_in' },
  { id: 'edge-diagnostics-capture', from: 'task-ingestion-hardening', to: 'tool-browser-extension', type: 'supports' },
  { id: 'edge-context-project', from: 'idea-agent-context', to: 'project-atlas', type: 'supports' },
]

export const timelineMoments: TimelineMoment[] = [
  {
    id: 'moment-voice',
    date: 'Jun 26',
    title: 'Voice-first second brain',
    description: 'The first shape was a fast voice entry layer for notes, ideas, and tasks.',
    nodeIds: ['idea-voice-entry', 'task-capture-console'],
  },
  {
    id: 'moment-harness',
    date: 'Jun 28 09:42',
    title: 'Agent Harness framing',
    description: 'The project became a PM portfolio piece around agent memory and context engineering.',
    nodeIds: ['project-deepseek', 'idea-agent-context', 'decision-jd-narrative'],
  },
  {
    id: 'moment-shift',
    date: 'Jun 28 11:15',
    title: 'Shift to AI Memory Atlas',
    description: 'The product moved from previous-chat convenience to long-term personal memory assets.',
    nodeIds: ['decision-shift-to-atlas', 'idea-memory-graph', 'failure-lost-chats'],
  },
  {
    id: 'moment-replay',
    date: 'Jun 28 12:04',
    title: 'Emotional value appears',
    description: 'Replay Mode turned the graph from storage into a story of how ideas grow.',
    nodeIds: ['artifact-replay-mode', 'question-memory-trust'],
  },
  {
    id: 'moment-export',
    date: 'Jun 28 15:21',
    title: 'Agent context export',
    description: 'Project Lens closes the loop by exporting memory back into agent work.',
    nodeIds: ['artifact-project-context-export', 'task-export-context', 'idea-agent-context'],
  },
]

export const atlasProjects: AtlasProject[] = [
  {
    id: 'project-atlas',
    title: 'AI Memory Atlas',
    summary:
      'A graph-first product demo that visualizes how human-AI collaboration grows into projects, decisions, tasks, artifacts, questions, and preferences.',
    status: 'MVP direction locked',
    decisionIds: ['decision-shift-to-atlas', 'decision-capture-supporting-flow'],
    taskIds: ['task-capture-console', 'task-export-context', 'task-ingestion-hardening'],
    artifactIds: ['artifact-replay-mode', 'artifact-project-context-export'],
    questionIds: ['question-memory-trust'],
  },
]
